services:
  mysql:
    image: mysql:9.3.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=53cret
      - MYSQL_DATABASE=customerdb
      - MYSQL_USER=yu71
      - MYSQL_PASSWORD=53cret
    ports:
      - "3309:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

volumes:
  mysql-data:
