openapi: 3.0.1
info:
  title: volte-provisioning
  version: sit
externalDocs:
  description: Confluence VoLTE Documentation
  url: https://confluence.xl.co.id/display/docsit/volte-provisioning
servers:
  - url: http://volte-provisioning-sit.api.devgcp.excelcom.co.id
    description: Generated server url
paths:
  /volte/v2/provisioning/productOrder:
    post:
      tags:
        - provision-controller
      operationId: productOrder
      parameters:
        - name: ax-touchpoint
          in: header
          required: false
          schema:
            type: string
        - name: ax-request_id
          in: header
          required: false
          schema:
            type: string
        - name: ax-request_at
          in: header
          required: false
          schema:
            type: string
            format: date-time
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationByRORq'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /volte/v1/rollback:
    post:
      tags:
        - provision-controller
      operationId: rollback
      parameters:
        - name: channel
          in: header
          required: false
          schema:
            type: string
        - name: ax-request_id
          in: header
          required: false
          schema:
            type: string
        - name: ax-request_at
          in: header
          required: false
          schema:
            type: string
            format: date-time
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /provisioning/v1/volte/{vendor}:
    post:
      tags:
        - provision-controller
      operationId: registrationAsync
      parameters:
        - name: vendor
          in: path
          required: true
          schema:
            type: string
        - name: channel
          in: header
          required: false
          schema:
            type: string
        - name: ax-request_id
          in: header
          required: false
          schema:
            type: string
        - name: ax-request_at
          in: header
          required: false
          schema:
            type: string
            format: date-time
        - name: Accept
          in: header
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/param'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
        '202':
          description: OK
          content:
            '*/*':
              schema:
                type: object
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
  /provisioning/v1/volte/{transaction}/{vendor}:
    post:
      tags:
        - provision-controller
      operationId: registrationSync
      parameters:
        - name: vendor
          in: path
          required: true
          schema:
            type: string
        - name: transaction
          in: path
          required: true
          schema:
            type: string
        - name: channel
          in: header
          required: false
          schema:
            type: string
        - name: ax-request_id
          in: header
          required: false
          schema:
            type: string
        - name: ax-request_at
          in: header
          required: false
          schema:
            type: string
            format: date-time
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/param'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
        '202':
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /volte/v1/check:
    get:
      tags:
        - provision-controller
      operationId: checkVolteReadiness
      parameters:
        - name: MSISDN
          in: query
          required: false
          schema:
            type: string
        - name: IMSI
          in: query
          required: false
          schema:
            type: string
        - name: IMEI
          in: query
          required: false
          schema:
            type: string
        - name: CELLID
          in: query
          required: false
          schema:
            type: string
        - name: CHANNEL
          in: header
          required: false
          schema:
            type: string
        - name: REQUESTID
          in: header
          required: false
          schema:
            type: string
        - name: REQUESTDATE
          in: header
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /volte/v1/:
    get:
      tags:
        - provision-controller
      operationId: currentProfile
      parameters:
        - name: channel
          in: header
          required: false
          schema:
            type: string
        - name: ax-request_id
          in: header
          required: false
          schema:
            type: string
        - name: ax-request_at
          in: header
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /volte/v1/{msisdn}:
    get:
      tags:
        - provision-controller
      operationId: currentProfile_1
      parameters:
        - name: msisdn
          in: path
          required: true
          schema:
            type: string
        - name: channel
          in: header
          required: false
          schema:
            type: string
        - name: ax-request_id
          in: header
          required: false
          schema:
            type: string
        - name: ax-request_at
          in: header
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/volte/v1/readiness/{msisdn}:
    get:
      tags:
        - volte-bicc-controller
      operationId: checkReadiness
      parameters:
        - name: msisdn
          in: path
          required: true
          schema:
            type: string
        - name: IMSI
          in: query
          required: false
          schema:
            type: string
        - name: IMEI
          in: query
          required: false
          schema:
            type: string
        - name: CGI
          in: query
          required: false
          schema:
            type: string
        - name: CHANNEL
          in: header
          required: true
          schema:
            type: string
        - name: TOUCHPOINT
          in: header
          required: true
          schema:
            type: string
        - name: REQUESTID
          in: header
          required: true
          schema:
            type: string
        - name: REQUESTAT
          in: header
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    Channel:
      type: object
      properties:
        id:
          type: string
    RegistrationByRORq:
      type: object
      properties:
        externalId:
          type: string
        channel:
          type: array
          items:
            $ref: '#/components/schemas/Channel'
        relatedParty:
          type: array
          items:
            $ref: '#/components/schemas/RelatedParty'
        channelValue:
          type: string
    RelatedParty:
      type: object
      properties:
        id:
          type: string
        '@referredType':
          type: string
    body:
      type: object
      properties:
        msisdn:
          type: string
        imsi:
          type: string
        vendor:
          type: string
    param:
      type: object
      properties:
        msisdn:
          type: string
        imsi:
          type: string
        imei:
          type: string
        pid:
          type: string
        charging:
          type: string
        pdptype:
          type: string
